---
- name: "Update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "Upgrade apt packages"
  become: yes
  apt:
    upgrade: yes

# - name: "Add nodejs"
#   become: yes
#   shell: curl --silent --location https://rpm.nodesource.com/setup_14.x | sudo bash -

- name: "Install nodejs"
  become: yes
  apt:
    name: ["nodejs", "npm"]

- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes

- name: "Create web directory"
  shell: mkdir ~/web

- name: "Copy index.js"
  copy:
    src: index.js
    dest: ~/web/index.js
    backup: yes

- name: "Run Script"
  shell: |
    cd ~/web
    pm2 start index.js -f 

- name: "Clean unwanted packages"
  become: yes
  apt:
    autoremove: yes